### ISSUE TITLE
getting posts by "friends of friends" only returning first one found

### ISSUE THREAD

**Issue by MattDekinder** [CMPUT404W17/FoundBook#119]
This is a test case failure which I've debugged a bit-- the service seems to be returning only the first post it finds. 

Posts ids actually returned: 1, 3, 4, 9, 10, 12, 13.

======================================================================
ERROR: test_author_can_see_friends_fof (fb.tests.PostTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matt/foundBook/fb/tests.py", line 200, in test_author_can_see_friends_fof
    self.visible_posts.get(id=self.posts[13].id)
  File "/home/matt/foundBook/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Post matching query does not exist.

**Comment by cujomalainey** [comment]
Thanks for finding this @MattDekinder, i wrote this test case knowing i forgot to implement this (which i did) thanks for reminding me
