### ISSUE TITLE
Everything breaks when deleting a remote server

### ISSUE THREAD

**Issue by gantonious** [CMPUT404W17/FoundBook#188]
author is None when checking is_remote

**Comment by cujomalainey** [comment]
I have a guess as to the cause of this, it appears the author generic foreign doesnt appear to be set to cascade on a delete. Therefore there might be author lookups happening after a delete on authors that no longer exist.

**Comment by cujomalainey** [comment]
Above comment is exactly what happens, when a server is deleted its authors are also deleted but the comments are orphaned. Going to make a routine on a delete of authors or remote authors to clean up comments.
