### ISSUE TITLE
User Image restrictions

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT404W17/FoundBook#22]
As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication.

**Comment by cujomalainey** [comment]
This user story is ambiguous as images are posts according to the JSON api, and post can be public, does that mean all posts with contentType cannot be public?

**Comment by MattDekinder** [comment]
I'm pretty sure this is about ensuring that the uri for images is protected with the same permissions as the post it's associated with

**Comment by cujomalainey** [comment]
That is still weird considering by the nature of the interface, an image (aka a post) inherits the permissions of the encapsulating post fields

**Comment by cujomalainey** [comment]
this is complete, images do not leave on unauthed connections
