### ISSUE TITLE
Restful API for admin

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT404W17/FoundBook#34]
As a server admin, I want a restful interface for most operations

**Comment by cujomalainey** [comment]
@gantonious Thoughts on this one? is it looking for an API to manage the remote servers and users?

**Comment by gantonious** [comment]
That's how I interpreted it as.

**Comment by cujomalainey** [comment]
Ok, maybe this is worth bumping, ill check where we are tonight before i do it

**Comment by cujomalainey** [comment]
I'm going to quickly stub this out
