### ISSUE TITLE
Can't post to author/posts

### ISSUE THREAD

**Issue by MattDekinder** [CMPUT404W17/FoundBook#51]
Line 36 of PostsAPI.py : 'post_body = json.loads(request.body) ' triggers the error: 
 "You cannot access body after reading from request's data stream" when I post to /author/posts

It looks like like the request object lacks the body attribute but the arguments I post are still in request.data. They're also a dictionary already so changing post_body = request.data now forwards that dictionary leading to another error: 

Cannot assign "[u'superuser']": "Post.author" must be a "Author" instance.

This should be reproducible with the ui form or a curl command

**Comment by MattDekinder** [comment]
RawPostDataException at /author/posts/

You cannot access body after reading from request's data stream

Request Method: 	POST
Request URL: 	http://localhost:8000/author/posts/
Django Version: 	1.10.5
Exception Type: 	RawPostDataException
Exception Value: 	

You cannot access body after reading from request's data stream

Exception Location: 	/home/matt/foundBook/venv/local/lib/python2.7/site-packages/django/http/request.py in body, line 264
Python Executable: 	/home/matt/foundBook/venv/bin/python
Python Version: 	2.7.12
Python Path: 	

['/home/matt/foundBook',
 '/home/matt/foundBook/venv/lib/python2.7',
 '/home/matt/foundBook/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/matt/foundBook/venv/lib/python2.7/lib-tk',
 '/home/matt/foundBook/venv/lib/python2.7/lib-old',
 '/home/matt/foundBook/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/matt/foundBook/venv/local/lib/python2.7/site-packages',
 '/home/matt/foundBook/venv/lib/python2.7/site-packages']

Server time: 	Sat, 11 Mar 2017 02:14:32 +0000

**Comment by cujomalainey** [comment]
Ok i'm looking into this right now, I may have fixed a bug related to this regarding auth

**Comment by cujomalainey** [comment]
@MattDekinder K there are some issues on your branch, im going to merge ours in because that should fix a lot of them

**Comment by cujomalainey** [comment]
@MattDekinder the merge fixed it, note that it is a Read operation from that endpoint so it is a GET.

**Comment by MattDekinder** [comment]
It wasn't a read while I was working on it. Please put the working API on the master branch

**Comment by cujomalainey** [comment]
That endpoint according to the [JSON spec](https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json) is only hit by GETs and only returns the latest posts, what are you trying to write to it?

**Comment by MattDekinder** [comment]
I'm no longer trying to write to /author/posts. The API as implemented on master branch currently is handling posts to author/posts not /posts.  No doubt this is an error but if it's been corrected somewhere then please update master branch.

**Comment by cujomalainey** [comment]
yep, just doing one fix then pulling into master
