### ISSUE TITLE
Private to only people on my host

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT404W17/FoundBook#8]
As an author, posts I create be private to only friends on my host

**Comment by MattDekinder** [comment]
Is this not part of the API? I understood this as only sending posts which correspond to friends on the "origin" host for the post. There is a setting in the request for this permission and we are currently allowing the client to specify the origin for a post.

I suppose we do need a way to add friends through the ui, though

**Comment by cujomalainey** [comment]
yes, we just need a way for you guys to specify who can view it
